version: "3.8"

services:

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    volumes:
      - "./:/var/www/html"
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports:
      - "${NGINX_PORT}:8080"
      - "${NGINX_SSL_PORT}:443"

  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
    build:
      context: .
      dockerfile: docker/php.dockerfile
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - "mailing_service:/var/lib/mysql"
    ports:
      - "3306:3306"

  adminer:
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    image: library/adminer:latest
    env_file:
      - .env
    ports:
      - "${ADMINER_PORT}:8080"

  mailhog:
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mailing_service:
    external: true