controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api:
    resource: "routes/resources/api/*.yaml"
    name_prefix: api_
    prefix: /

index:
    path: /
    controller: App\Controller\BaseApiController::index
    methods: GET

health:
    path: /health
    controller: App\Controller\BaseApiController::health
    methods: GET