controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api:
    resource: "routes/resources/api/*.yaml"
    name_prefix: api_
    prefix: /

web:
    resource: "routes/resources/web/*.yaml"
    name_prefix: web_
    prefix: /