parameters:
    corsAllowOrigin: "%env(CORS_ALLOW_ORIGIN)%"
    mailSenderNameFallback: "%env(MAIL_SENDER_NAME_FALLBACK)%"
    mailSenderEmailFallback: "%env(MAIL_SENDER_EMAIL_FALLBACK)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $corsAllowOrigin: '%corsAllowOrigin%'
            $mailSenderNameFallback: '%mailSenderNameFallback%'
            $mailSenderEmailFallback: '%mailSenderEmailFallback%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\Api\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
