parameters:
    corsAllowOrigin: "%env(CORS_ALLOW_ORIGIN)%"
    mailSenderName: "%env(MAIL_SENDER_NAME)%"
    mailSenderAddress: "%env(MAIL_SENDER_ADDRESS)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $corsAllowOrigin: '%corsAllowOrigin%'
            $mailSenderName: '%mailSenderName%'
            $mailSenderAddress: '%mailSenderAddress%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\Api\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
