parameters:
    corsAllowOrigin: "%env(CORS_ALLOW_ORIGIN)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $corsAllowOrigin: '%corsAllowOrigin%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\Api\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
